# Generated by Django 5.1.1 on 2024-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('photo', models.URLField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('balcony', models.BooleanField()),
                ('bath', models.BooleanField()),
                ('furnished', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
